a = input('Digite algo: ')
# A letra 'f' antes do das aspas substitui o 'format'
print(f"Você digitou: '{a}'")
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número?  {a.isnumeric()}')
print(f'É alfabeto? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está captalizado? {a.istitle()}')
